### ISSUE TITLE
Capacité "élu du seigneur"

### ISSUE THREAD

**Issue by Kyrantox** [Zakarik/foundry-knight#101]
Bonjour, 

Lorsque je met l'effet élu du seigneur (permet d'augmenter le maximum d'aspect et d'aspect exceptionnel d'un aspect). Je suis toujours bloqué à 20 en aspect et 10 en aspects exceptionnel.
Plus largement, sur une capacité, les bonus liés au bouton "Augmente le maximum d'un aspect" n'applique pas les bonus renseignés.

J'ouvre simplement l'issue à titre d'information, parce que le problème est facilement contournable en rajoutant des succès bonus ou des modificateurs à la main.

En espérant que ce ne soit pas un problème tenace.

**Comment by Zakarik** [comment]
Devrait être corrigé dans la prochaine version.
