### ISSUE TITLE
Les boutons de restaurations ne fonctionnent plus avec la V11

### ISSUE THREAD

**Issue by Florleseige** [Zakarik/foundry-knight#102]
Bonjour,

Les boutons de restaurations (santé, énergie, armure et espoir) ne fonctionnent plus.

Merci :)

**Comment by Florleseige** [comment]
Visiblement il y a des modules et capacités qui ont le même soucis.

**Comment by Zakarik** [comment]
Devrait être corrigé dans la prochaine version.
