### ISSUE TITLE
Amélioration des Overdrives

### ISSUE THREAD

**Issue by Florleseige** [Zakarik/foundry-knight#103]
Bonjour,

Dans les "Bonus" que peuvent donner les Overdrives, serait-ce possible de donner un bonus aux points de vie comme pour l'armure ?
Je pense notamment à rendre le système compatible comme le 3eme OD d'endurance qui donne 6 PV.

Merci d'avance

**Comment by Zakarik** [comment]
Ce sera ajouté à la prochaine version.
