### ISSUE TITLE
Boucle infini sur une fiche d'acteur

### ISSUE THREAD

**Issue by Florleseige** [Zakarik/foundry-knight#106]
Bonjour,

Pour une raison inconnu, nous avons une boucle infini de warnings sur une fiche qui bloque complètement l'utilisation de la fiche.

Voici le warning : 
![image](https://github.com/Zakarik/foundry-knight/assets/14095403/3b999fe4-d9ed-43fe-8377-c889cf25bf72)

Merci d'avance !

**Comment by Florleseige** [comment]
Voici la fiche de l'acteur : 
[fvtt-Actor-praxis-mar-pUTwXx9ddOkHmEgA.json.txt](https://github.com/Zakarik/foundry-knight/files/11646709/fvtt-Actor-praxis-mar-pUTwXx9ddOkHmEgA.json.txt)

**Comment by Zakarik** [comment]
Comme on en a discuté, je clos ça.
A réouvrir si le problème se représente dans la prochaine version.
