### ISSUE TITLE
Images manquantes

### ISSUE THREAD

**Issue by DjLeChuck** [Zakarik/foundry-knight#108]
Salut Zakarik,

En réinstallant le système de 0, je vois qu’il manque au moins deux images : `/assets/icons/logo.webp` et `/assets/icons/logoCircle.png`

**Comment by Zakarik** [comment]
Comment ça, il manque ?

**Comment by DjLeChuck** [comment]
@Zakarik ouvre la console de debug tu verras les messages d'erreur de fichier introuvable
Et ils ne sont effectivement pas dans le dossier d'installation du module alors qu'ils sont bien appelés dans les CSS.

**Comment by Zakarik** [comment]
C'est une erreur, ces images ne devraient pas être appelées.
Un oubli d'un travail en cours, j'y retirerai.
