### ISSUE TITLE
Warning au lancement d'un monde

### ISSUE THREAD

**Issue by Florleseige** [Zakarik/foundry-knight#111]
Bonjour,

Voici un warning qui survient plus de 9000 fois au lancement d'un de mes mondes :
![image](https://github.com/Zakarik/foundry-knight/assets/14095403/1b35a4e1-5552-4271-a19b-987426bf3deb)

Merci encore pour le super travail !

**Comment by Zakarik** [comment]
Je n'ai pas ça chez moi, tu as moyen d'envoyer ton monde ?
