### ISSUE TITLE
Erreur pour passer une arme du Rack à En main

### ISSUE THREAD

**Issue by Florleseige** [Zakarik/foundry-knight#112]
Bonjour,

Il y a une erreur qui arrive lorsqu'on essaye de passer une arme (qui a un Champs de Force) depuis le Rack à En main :

![image](https://github.com/Zakarik/foundry-knight/assets/14095403/2c6ae134-bff0-4b66-bb33-afa7d80ac5c3)

Merci beaucoup :)

**Comment by Zakarik** [comment]
Ca devrait être corrigé.
