### ISSUE TITLE
Disparition des armures après la mise à jour

### ISSUE THREAD

**Issue by Florleseige** [Zakarik/foundry-knight#113]
Bonjour,

Après la mise à jour, j'ai 3 acteurs sur mon monde qui ont perdu leurs armures.

il m'est impossible d'ajouter une armure à ces acteurs. Ni en cliquant sur le bouton "Créer l'armure", ni en drag & drop une armure du compendium.

Si j'exporte et je réimporte les armures j'ai le même soucis.

Voici mes 3 acteurs :

1. [fvtt-Actor-ebene-de-brume-OYb4xe2E8r3Jx0VO.json.txt](https://github.com/Zakarik/foundry-knight/files/11714265/fvtt-Actor-ebene-de-brume-OYb4xe2E8r3Jx0VO.json.txt)
2. [fvtt-Actor-gueritarish-undalavalak-itupEYuWNL9QVE2s.json.txt](https://github.com/Zakarik/foundry-knight/files/11714269/fvtt-Actor-gueritarish-undalavalak-itupEYuWNL9QVE2s.json.txt)
3. [fvtt-Actor-joseph-margoulin-U3l49IeumA4I4wD0.json.txt](https://github.com/Zakarik/foundry-knight/files/11714270/fvtt-Actor-joseph-margoulin-U3l49IeumA4I4wD0.json.txt)

Je reste à disposition.

**Comment by Zakarik** [comment]
Ca devrait être corrigé.
