### ISSUE TITLE
Valeur de bouclier des bandes

### ISSUE THREAD

**Issue by Kyrantox** [Zakarik/foundry-knight#114]
Bonjour, 

Toute petite issue, la valeur de bouclier ne s'actualise pas sur les bandes uniquement.
![image](https://github.com/Zakarik/foundry-knight/assets/43754117/84e4b41f-990c-4875-a44e-69a75da0541a)

Encore merci pour les Màj récentes ^^.

**Comment by Zakarik** [comment]
C'est corrigé.
