### ISSUE TITLE
Compatibilité avec le module Status Icon Encounter

### ISSUE THREAD

**Issue by Kyrantox** [Zakarik/foundry-knight#115]
Bonjour,

J'ai de nouveau le problème avec Status Icon Encounter, les PJ et PNJ sont touchés.

![image](https://github.com/Zakarik/foundry-knight/assets/43754117/917de97f-e6c7-4ef3-8e06-4d30dd40f955)

Désolé d'être le casse couille de service avec ce module ^^'.

Bon courage !

**Comment by Zakarik** [comment]
Tu peux m'envoyer ton monde ? J'arrive pas a tester chez moi.

**Comment by Kyrantox** [comment]
Oui pardon, il s'agit bien du module "Status Icon Counter". Pardon, je me suis trompé dans le nom du module.
Je vous ai envoyé en MP mon monde.

**Comment by Zakarik** [comment]
Bon, d'après les tests que j'ai faits, la dernière mise à jour doit avoir réglé le problème (3.13).
Je te laisse confirmer / infirmer ça et clore ou non l'issue.

**Comment by Kyrantox** [comment]
J'ai personnellement encore le problème uniquement sur les PNJ type chevalier.

![image](https://github.com/Zakarik/foundry-knight/assets/43754117/14d3b925-a5a8-4693-aae7-30279ca278c0)

J'ai pris le screen avec l'exemple de Gideon pour que vous puissiez tester avec un acteurs du Compendium.
Je ne sais pas si ça peut vous aider mais je suis encore sur la version 10 build 303 de Foundry et ma version de Status Icon Counters est 2.0.16.
Si le problème ne survient pas sur la dernière version de Foundry / Status Icon Counters, je ferais la migration du monde et les mises à jours de mon côté.

**Comment by Zakarik** [comment]
Je n'ai pas ce problème de mon côté.
Je peux avoir ton monde pour voir ?

**Comment by Kyrantox** [comment]
Je l'envoie comme d'habitude en MP sur discord

**Comment by Zakarik** [comment]
Ce sera corrigé dans la prochaine version.
À noter que ça nécessitera juste une ouverture des fiches qui ont ce problème pour qu'il soit résolu.
