### ISSUE TITLE
Problème améliorations ornementales sur modules

### ISSUE THREAD

**Issue by Kyrantox** [Zakarik/foundry-knight#116]
Bonjour, 

j'ai découvert un bug récemment.
Lorsque j'ajoute une amélioration ornementale sur les modules (comme les griffes par exemple), l'amélioration n'est pas visible et bloque l'ouverture de la fiche de modification du module sur lequel on a mis l'amélioration.

Bon courage ^^.

**Comment by Zakarik** [comment]
Ce sera corrigé dans la prochaine version.
