### ISSUE TITLE
Calcul Défense/Réaction

### ISSUE THREAD

**Issue by Kyrantox** [Zakarik/foundry-knight#117]
Il y a une erreur sur le calcul de défense et réaction sur les fiches PJ.

![image](https://github.com/Zakarik/foundry-knight/assets/43754117/cef6cc79-c263-4427-b47d-5ee1bad6651d)

![image](https://github.com/Zakarik/foundry-knight/assets/43754117/6c6e6096-d57d-4b30-8c96-d807173bf801)

Encore une fois, je suis sur Foundry 10 build 303. Je ne sais pas si le problème est présent sur le version 11.

**Comment by Zakarik** [comment]
Je pense avoir trouvé le problème, qui se situerait uniquement dans l'affichage du détail.
Serait-il possible de m'envoyer le personnage, que je puisse jeter un coup d'oeil si c'est bien le cas ?

**Comment by Kyrantox** [comment]
Je l'envoie en MP. Tous mes PJ sont touchés par le bug

**Comment by Zakarik** [comment]
Ce sera donc bien corrigé dans la prochaine version !
J'en profite pour t'expliquer : En gros, être membre de la section Kraken rajoute +1 en défense et réaction, qui n'était pas affiché dans le calcul.

Donc juste un bug d'affichage.
