### ISSUE TITLE
Bug sur méta-armure (spoiler)

### ISSUE THREAD

**Issue by Earnould3** [Zakarik/foundry-knight#120]
Bonjour,

Déjà un grand merci d'avoir développé un système si agréable à jouer et à manipuler sur Foundry.
Je viens d'accéder a l'armure Berserk et j'ai remarqué que les boutons en mode rage sont très complets, que ce soit pour monter le niveau de rage, prendre des dégâts, regagner de l'espoir etc...

Cependant, même au niveau 3 de rage, l'interface ne permet pas de lancer le jet de dégâts du mode Blaze (qui s'active automatiquement  au palier 3 de rage). Je ne peux pas non plus le lancer depuis le menu du mode illumination puisque je n'ai pas choisi la capacité Blaze. Je ne sais pas si il s'agit d'un bug ou d'un oubli mais serait-il possible d'avoir un bouton en plus pour lancer le jet correspondant aux dégâts de Blaze.

Merci beaucoup, cordialement

**Comment by Zakarik** [comment]
Ca doit être corrigé normalement !
J' ai ajouté un bouton au mode rage qui fait la même chose que le mode Blaze.
