### ISSUE TITLE
(Suggestion) Possibilité d'avoir un bouton "dégâts"

### ISSUE THREAD

**Issue by Cybninja33** [Zakarik/foundry-knight#122]
Salut Zak,

Depuis que j'utilise ta fiche de personnage, je trouve qu'il y a des infos "inutiles" lors du lancer de jet concernant une attaque. Je m'explique :

![image](https://github.com/Zakarik/foundry-knight/assets/136223502/d46fe74e-02a5-4a04-80b7-1175f21e4ad0)

Lorsque une attaque est effectuée comme c'est dans l'image, il y a les infos concernant si le jet à fait un succès, un grand succés un échec ou un échec critique. Mais il y a aussi les infos concernant l'ensemble des dégâts fait sur un seul individus et les dégâts de violence. Sauf qu'en réalité, c'est plusieurs infos (dégâts et violence) qui sont pas forcément nécessaire si il y a un échec. De même lorsqu'on attaque une cible, il y a pas besoin d'avoir les infos de violence et inversement.

De ce fait je me suis posé la question si il y avait possibilité d'avoir juste les infos lors du test puis d'avoir le choix, si ce dernier réussis, d'avoir le jet de dégâts ou le jet de violence ?

Ce qui, à mon sens, ferait une meilleur lecture pour le MJ et pour les joueurs.

Si ce n'est pas possible, ce n'est pas grave. Ce n'est qu'une suggestion. Et merci de m'avoir lu jusqu'au bout.

**Comment by Zakarik** [comment]
Je pense que la dernière mise à jour doit répondre à ta demande !
