### ISSUE TITLE
Problème : Style de combat précis

### ISSUE THREAD

**Issue by alexpouteau** [Zakarik/foundry-knight#126]
Bonjour, 

C'est à nouveau moi, cette fois-ci tout est à jour et j'ai un soucis avec les attaque en style précis. Dès qu'on utilise le style et qu'on sélectionne un 3eme caractéristique dans le panel adéquat :
![image](https://github.com/Zakarik/foundry-knight/assets/34100229/ac857915-c09a-4c68-a114-3236d09b1d7d)
Le lancé ne se fait pas et ce message d'erreur apparait dans la console :
![image](https://github.com/Zakarik/foundry-knight/assets/34100229/d246be6f-138e-4756-9287-348e6dd00f34)

Si aucune caractéristique sélectionner dans le panel précis n'est sélectionnée, le jet semble fonctionner normalement.

**Comment by Zakarik** [comment]
C'est corrigé.
