### ISSUE TITLE
Amplificateur de frappe sur PNJ

### ISSUE THREAD

**Issue by Kyrantox** [Zakarik/foundry-knight#129]
Bonjour Zakarik,

Je reviens te casser les pieds ^^'.
Lorsque j'utilise le module amplificateur de frappe sur un PNJ, les dés supplémentaire de l'amplificateur ne sont pas pris en compte.
Voici l'exemple sur l'épée cinétique d'un de mes PNJs.

L'épée cinétique fait 7d6 de dégât .

![image](https://github.com/Zakarik/foundry-knight/assets/43754117/ca1a10f1-24ab-46a3-bbfe-4275e733ed21)

J'active bien les 6d6 bonus sur la fiche de jet

![image](https://github.com/Zakarik/foundry-knight/assets/43754117/32624b90-b6c3-4bb4-a99f-9f9c29dab4ef)

Cependant lors du calcul des dommages, je n'ai que les dés de dégâts de l'arme initiale soit 7d6 au lieu de 13d6

![image](https://github.com/Zakarik/foundry-knight/assets/43754117/e9c64aee-ace4-4abd-8110-4111592f09ee)

PS : j'ai juste caché le nom du PNJ au cas ou un joueur passerai par là :)

**Comment by Zakarik** [comment]
Ce sera corrigé dans la prochaine mise à jour.
