### ISSUE TITLE
[Suggestion] Automatisation des soins sur une autre cible.

### ISSUE THREAD

**Issue by Angor-de-Redjak** [Zakarik/foundry-knight#130]
Salut !
Autant pour les dégâts, il y a des histoires de réductions & cie, autant tout ce qui est soins, réparation d'amure ou regain d'énergie c'est assez direct.
Est-ce qu'il ne serait pas possible de target un token avec son perso et d'utiliser une méthode permettant de regagner des points et que ça les ajoute automatiquement ? Je pense notamment aux nods et au mode Mechanic de la Priest.

**Comment by Florleseige** [comment]
Fait dans : https://github.com/Zakarik/foundry-knight/pull/193
