### ISSUE TITLE
Capacité manquante sur les Noctes du compendium

### ISSUE THREAD

**Issue by Tergeist** [Zakarik/foundry-knight#131]
Dans le compendium, les Noctes ne disposent pas de la capacité "Ignore CDF" qu'ils ont dans le Bestiaire officiel.

**Comment by Kyrantox** [comment]
Salut Tergeist,

Zakarik ne s'occupe que du système de Knight sur foundry, pas le compendium.
Je t'invite à ouvrir une issue sur le github de DjLeChuck https://github.com/DjLeChuck/foundryvtt-knight-compendium.
C'est lui qui s'occupe du compendium ;).
