### ISSUE TITLE
Bug mineur : Affichage CdF Véhicule

### ISSUE THREAD

**Issue by Kyrantox** [Zakarik/foundry-knight#132]
Salut Zakarik,

En bidouillant, j'ai remarqué que les nouveaux véhicules n'avaient pas leurs valeurs de CdF affiché correctement. Un peu comme les bandes et leurs boucliers fut un temps.

![image](https://github.com/Zakarik/foundry-knight/assets/43754117/41f46ef1-657c-4b9f-a145-303ebf677eaf)

**Comment by Zakarik** [comment]
Ca va être corrigé sous peu.
