### ISSUE TITLE
Impossible d'ajouter un effet sur un module de type arme

### ISSUE THREAD

**Issue by DjLeChuck** [Zakarik/foundry-knight#14]
1. Créer un module
2. Indiquer que c'est une arme
3. Essayer de lui ajouter un effet via le bouton `Modifier les effet` (d'ailleurs il manque un `s` 😄 )

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'arme')
    at module-sheet.mjs:126:20
    at Array.forEach (<anonymous>)
    at HTMLAnchorElement.<anonymous> (module-sheet.mjs:125:29)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
```

**Comment by DjLeChuck** [comment]
En corrigeant les `data-path` problématiques dans `module-sheet.html`, l'ajout fonctionne, mais pas l'enregistrement qui va planter à son tour dans `effets-dialog.mjs`

**Comment by Sphins** [comment]
le même problème ce présente pour les améliorations dans le meme cas
