### ISSUE TITLE
Remarque et bug varié

### ISSUE THREAD

**Issue by IDDragnil1** [Zakarik/foundry-knight#141]
Bonjour @Zakarik, déjà merci pour tout le travaille accomplie 

Pour parler des pb que j'ai trouver il y a : 
- Les compagnons du druid n'ont pas d'image sur leurs tokens 
- Certaine fois les armes n'ont pas les bons mots clé et les bons dégâts (ils ont celle d'une autre arme qui est déracker) (bug que je n'arrive pas à reproduire, mais qui se passe 1/2 fois par séance de combat)
- Quand j'active le pod roquette dans un véhicule, il perd sont CdF
- De plus certaine arme ne veulent pas lancer leurs dégâts avec ça comme message
![image](https://github.com/Zakarik/foundry-knight/assets/133610200/6fe0a29c-801c-42ca-8e49-8f004b667875)

**Comment by Kyrantox** [comment]
Bonjour @Zakarik,

Je plussoie les points énumérés ci-dessus. Et effectivement le bug des "mauvais effets" de l'arme apparait de temps à temps mais je n'arrive pas non plus à le reproduire à ma convenance.
De plus, je pense qu'il serai sympa de pouvoir également personnaliser le token des pets en plus de l'image. 😉

**Comment by Zakarik** [comment]
Pour ce que j'ai pu constater, c'est corrigé ! Je ferme ça, donc.
