### ISSUE TITLE
[Bug] Méta-Armure de légende

### ISSUE THREAD

**Issue by Kyrantox** [Zakarik/foundry-knight#143]
Bonjour Zakarik,

La liste déroulante des caractéristiques pour les bonus à l'attaque et aux dégâts sur les objets de types Méta-Armure de légende n'affichent pas les caractéristiques.

![image](https://github.com/Zakarik/foundry-knight/assets/43754117/b6c03ade-18c7-4bcf-9251-de77bafbc827)

**Comment by Zakarik** [comment]
Corrigé.
