### ISSUE TITLE
Bug module

### ISSUE THREAD

**Issue by IDDragnil1** [Zakarik/foundry-knight#148]
Salut, j'ai regardé dans les options des modules et j'ai trouvé 2 bugs 

Le premier, c'est dans Applique / Possède un effet : Ça ne fait rien sur les armes et jet de dégâts.
Le deuxième, c'est dans "Peut devenir une créature indépendante" Il n'est pas possible de rajouter d'armes.

**Comment by Zakarik** [comment]
Pour le premier, c'est le fonctionnement normal.
C'est à dire que c'est juste pour indiquer qu'un module possède certains effets (Il y en a quelques-uns comme ça).

Pour le second, effectivement, petite erreure, je corrige ça et la mise à jour sera en ligne sous peu.
