### ISSUE TITLE
[Bug] L'effet 'Erzatz Rogue' du camouflage optique ne s'applique pas sur le Longbow

### ISSUE THREAD

**Issue by sdurrheimer** [Zakarik/foundry-knight#151]
Lorsqu'on ajoute l'effect 'Silencieux' (dépense énergie) lors de la préparation d'un tir avec le Longbow (attaque surprise), le bonus en dés (attaque et dégâts) de l'Erzatz Rogue ne s'applique pas.

Exemple qui fonctionne avec l'arbalètte magnétique qui possède l'effet 'Silencieux' sur son profil de base, après avoir activé le module de camouflage optique:

![image](https://github.com/Zakarik/foundry-knight/assets/1931038/e293b87a-b372-42b0-99f1-6a86dc110a2e)

(on remarque aussi que le module 'Camouflage optique' s'est bien désactivé après l'attaque)

Example qui ne fonctionne pas avec le Longbow, effect 'Silencieux' appliqué lors de la préparation du tir et après avoir activé le module de camouflage optique:

![image](https://github.com/Zakarik/foundry-knight/assets/1931038/59e22ec9-21cd-4516-8234-7a479ce9d9cb)

(on remarque aussi que le module 'Camouflage optique' ne s'est pas désactivé après l'attaque)

**Comment by Zakarik** [comment]
Corrigé dans la dernière mise à jour (normalement).

**Comment by sdurrheimer** [comment]
Top, merci beaucoup !

![image](https://github.com/Zakarik/foundry-knight/assets/1931038/81bf6c11-cf76-4fd6-b1df-1a9cf05fcc27)
