### ISSUE TITLE
[Suggestion] Affichage Overdrive

### ISSUE THREAD

**Issue by Kyrantox** [Zakarik/foundry-knight#161]
Bonjour Zakarik,

Je pense que ça simplifierai la lecture des fiches si dans l'onglet "module" des fiches PJ, les OD sont affiché séparément des modules.

Bon courage pour ce qui reste à rattraper, il y a pas mal d'issues ;)

**Comment by Zakarik** [comment]
Ce sera mis en place à la prochaine mise à jour.
