### ISSUE TITLE
amélioration Boost ?

### ISSUE THREAD

**Issue by ZantiguiDialo** [Zakarik/foundry-knight#163]
Sur Knight System, ils ont créé une amélioration BOOST avec un niveau de puissance (BOOST 10 permet d'ajouter 10 D6 aux dommages).
Dans le système de jeu, je ne vois pas la possibilité d'avoir cet effet or ca permet aux joueurs de comprendre le niveau d'amélioration nécessaire.

**Comment by Zakarik** [comment]
Sera intégré à la prochaine mise à jour.
