### ISSUE TITLE
[Bug] Module créatures indépendantes

### ISSUE THREAD

**Issue by Kyrantox** [Zakarik/foundry-knight#164]
Bonjour Zakarik,

J'étais en train de bidouiller des modules pour mes joueurs et lorsque j'ai voulu m'attarder sur le module prestige "Meute du Loup", j'ai remarqué quelque soucis.
Il n'y a pas la possibilité de renseigner de cohésion pour les bandes, ni de points de santé si on le souhaite pour les PNJ.
![image](https://github.com/user-attachments/assets/63ea4eee-dbfa-47d9-9333-f13067578b86)

De plus, lorsque je clique sur le bouton pour créer la créature, la valeur d'énergie de la fiche disparait (probablement à cause d'une valeur undefined).
![image](https://github.com/user-attachments/assets/7ca35690-05cf-464a-8c17-43aaa9a95c07)
![image](https://github.com/user-attachments/assets/1c3198bf-5738-45d3-a667-6e3933edefe1)

PS : Pour les MJs rencontrant se problème, la solution de contournement est simplement de créer les fiches des créatures/bandes en dur et de simplement utiliser le module pour consommer l'énergie.

**Comment by Zakarik** [comment]
Corrigé dans la dernière mise à jour normalement !
