### ISSUE TITLE
(bug) Fiche armure endommagée à la fermeture

### ISSUE THREAD

**Issue by Bruno-B0** [Zakarik/foundry-knight#167]
Bonjour,

J'ai remarqué ceci : 
Sur la Paladin, si je lance le Shrine, puis que je repasse en tenue civile sans mettre fin au Shrine, la fiche plante (impossible d'arrêter le shrine, l'énergie ne fonctionne plus correctement, bref, faut refaire des grosses modifs sur la fiche ou remettre un backup. 

Bonne journée.

Bruno

**Comment by Zakarik** [comment]
Corrigé dans la dernière version.
