### ISSUE TITLE
[BUG] Champ "Bonus de champ de force / Mètre" du mode Goliath

### ISSUE THREAD

**Issue by Kyrantox** [Zakarik/foundry-knight#169]
Salut Zakarik,

Lorsque l'on déverrouille le mode Goliath pour modifier le champ "Bonus de champ de force / Mètre", il revient toujours à 1.
La modification n'est jamais effective.

Bon courage pour les fixs ;).

**Comment by Zakarik** [comment]
Merci pour le retour !
Ce sera corrigé dans la prochaine mise à jour (actuellement en beta)
