### ISSUE TITLE
[Amélioration] Bouton Restaurer l'Espoir 

### ISSUE THREAD

**Issue by Relkem** [Zakarik/foundry-knight#170]
Salut Zakarik,

Dans la fiche des PJ, onglet Options, on a la possibilité de restaurer santé/énergie/armure et Espoir.
Est-il possible de mettre un disclaimer lorsque l'on clique dessus ? 
Histoire d'éviter la fausse manip sur cette restauration.

Et également s'il est possible de rendre cette option accessible uniquement par le MJ.

**Comment by Zakarik** [comment]
Ce sera dans la prochaine mise à jour.
