### ISSUE TITLE
[Suggestion] Donner plus d'information pour oblitération

### ISSUE THREAD

**Issue by Tenariel** [Zakarik/foundry-knight#178]
Apres avoir eu 2 de mes PJs qui utilisent une arme avec l'effet oblitération (dont 1 avec l'effet <boost>), je me suis rendu compte qu'indiquer la valeur max (indiqué comme la valeur de destructeur) pourrait être utile.

Pour rappel, l'effet oblitération:

Ces équipements particulièrement puissants infligent des dégâts considérables aux cibles les moins résistantes. Contre un ennemi de type hostile, ils infligent toujours le résultat maximal des dés de dégâts, comme si chacun des dés avait fait 6. Les dés ne sont simplement pas lancés. Si l’arme possède l’effet [dispersion], chaque cible hostile touchée subit le maximum de dégâts.

**Comment by Zakarik** [comment]
Il me faudrait plus d'information sur ce que tu entends par là.
Actuellement, quand on fait le jet, ça met le résultat maximum.
Ca ne suffit pas ?

**Comment by Tenariel** [comment]
il est vrai que je n'ai pas les dernieres modification car j'attends de finir ma mission actuelle car ca va utiliser un systeme qui a pas du être bc tester (les gros machins pour éviter de spoil).

dans ma version actuelle 3.29.5, je n'ai rien pour l'effet oblitération :

![image](https://github.com/user-attachments/assets/70a0ec1b-42f9-47e4-99c6-a4f1b113a2cf)

Si dans la dernière version il y a cette indication, tu peux fermer ce ticket !

**Comment by Zakarik** [comment]
(fais pas attention aux dégâts, c'était pour montrer l'affichage)
Est-ce que tu considères que c'est bon comme ça ?
![image](https://github.com/user-attachments/assets/46ac62ba-2375-4351-a3f2-a9a436aedbf0)

**Comment by Kyrantox** [comment]
Je confirme que dans la 3.32.2 tu as ce que tu cherches @Tenariel . Lors du jet des PJ tu as des bouton pour maximiser les dommages ou la violence.

![image](https://github.com/user-attachments/assets/2e5a5205-32e8-4115-9e4b-cb83f6b1389a)

Et pour les "gros machin" va falloir que je fasse un tour dessus pour faire une liste si il y a plus de changement à faire dessus que l'issue #152  que j'avais déjà ouvert

**Comment by Kyrantox** [comment]
De plus le résultat et toujours les dégâts maximum si le joueur clique pour activer l'oblitération
