### ISSUE TITLE
English Translation Issues

### ISSUE THREAD

**Issue by TechieDragonKnight** [Zakarik/foundry-knight#186]
Hi Zakarik,

I posted this in the Antre Monde Editions Knight GM Channel, but I am reposting it here just so people can see in multiple places when the issues are resolved. It looks like since I last posted some problem areas have gotten worse.

Albeit with the Babel module and/or some other issue, here are the faulty compendium areas:

1. Module 1-3 compendiums still has the names of the items and descriptions in french. Module 4 on the compendium list pop up have all the correct english names, but when you click on any of the entries the french name and descriptions show up.
2. Meta-armour 1-4 compendiums showing french names on the pop up list and french name/descriptors when clicking on any given entry. The Meta-armour Legendary compendium shows the translations just fine.
3. Under the folder CodexFM4, the Incapacitating Polymer still shows its french name on the pop up list and the item entry, but the item description is in english. 
4. The Overdrive compendium is misspelled as 'Orverdrive' 

These are the only issues I have noticed with the compendiums as it relates to the English Babel translations. Would also be happy to help with proofreading if requested.

**Comment by Zakarik** [comment]
This is normally corrected (for Orverdrive, it will be corrected shortly - it's been sent, it just needs to be validated).
