### ISSUE TITLE
recueil de bugs decouverts en jouant

### ISSUE THREAD

**Issue by Aradhil** [Zakarik/foundry-knight#187]
pas de décompte des grenades utilisées
on ne voit pas non plus les réussites sur les flashbang (pour connaitre le résultat choc)

 il n'y a pas le choix du type de munition (balle grappe/ balle explosif...) dans la fenetre de combat 

Le retour a l'état precedent d'évolution de l'armure ne fonctionne pas

**Comment by Aradhil** [comment]
onglet pour faire apparaitre l'Egide

**Comment by Zakarik** [comment]
Sera corrigé dans la prochaine mise à jour.
