### ISSUE TITLE
[Bug] Fiche méta-armure

### ISSUE THREAD

**Issue by Kyrantox** [Zakarik/foundry-knight#188]
Salut Zakarik,

De ce que j'ai écumé, voici une liste de problèmes rencontrés : 
- Les munition d'amélioration ne sont plus accessible (munitions explosives, IEM etc.)
- Les grenades ne sont plus décompté
- Les méta-armures de légende ne sont plus équipable. Elles apparaissent moins d'une seconde avant de disparaître. Les méta-armures de légende anciennement équipé ont l'air de fonctionner.
- De plus, il n'est plus possible de revenir à un état antérieur pour les évolutions

Bon courage ;)

**Comment by Zakarik** [comment]
Sera corrigé dans la prochaine version.
Pour les munitions, j'ai remis celles que je pensais, s'il en manque, ne pas hésiter à me le dire, car je dois décider indépendamment desquels j'affiche, mais c'est très simple à faire.
