### ISSUE TITLE
[Bug] capacité ultime foudre de guerre

### ISSUE THREAD

**Issue by Kyrantox** [Zakarik/foundry-knight#189]
Salut Zakarik,

Je me suis également rendu compte que la capacité ultime de la warrior ne fonctionne pas.
Je ne sais pas si c'était une capacité fantôme (en gros une capacité qui n'avait pas d'effet système mais sert juste à titre informatif), mais en tout cas mon PJ ne peut choisir qu'un seul mode.

Si c'était bien une capacité fantôme, je pense qu'il serai cool que l'on puisse choisir le deuxième type à activer sur le bandeau de la capacité ultime. Je pense qu'il sera plus simple de gérer comme ça le fait que l'activation du deuxième mode est gratuit.

Dès que je peux j'essaierai de faire un bon tout plus ou moins exhaustif du système pour écumer les problèmes.

Bon courage zakarik, je sens que tu vas avoir du travail ;).

**Comment by Zakarik** [comment]
Ce n'est pas une capacité fantome, juste un oubli.
Sera corrigé dans la prochaine mise à jour.
