### ISSUE TITLE
[Bug] Capacité ultime Shaman

### ISSUE THREAD

**Issue by Kyrantox** [Zakarik/foundry-knight#190]
Salut Zakarik, c'est encore le chieur de service !

Je suis en train de faire le tour de ce qui marche pas trop bien, j'essaierai de te faire une issue bien complète dès que je peux. Pour l'instant je fais juste ce qui ne marche pas sur ma table actuellement.

Il me semble que c'était déjà le cas de base et que ça n'a rien à voir avec le Data model mais la mise à jour du mode ascension de "deux fois vivant" copie aussi les modules prestige ainsi que la capacité ultime deux fois vivant hors qu'il ne le devrait pas. Ce qui est cocasse, je dois l'admettre, lorsque mon joueur a voulu utilisé deux fois vivant sur son double...
M'enfin c'était marrant quand même.

Bref, bon courage ! ;)

**Comment by Zakarik** [comment]
Ce sera corrigé à la prochaine mise à jour
