### ISSUE TITLE
[Bug] Munitions arme à distance

### ISSUE THREAD

**Issue by Kyrantox** [Zakarik/foundry-knight#191]
Je sais que tu dois plus me voir en peinture, pardonne moi.

Les munitions suivantes ne sont pas choisissable lors du jet : 
- Munitions drones
- Munitions Hyper vélocité
- Munitions subsoniques

Même si elle ne sont pas sélectionnable, les munitions subsonique et hyper vélocité sont directement prises en compte dans le jet. Mais ce serai bien de les rajouter dans la liste par soucis d'uniformisation.
Les munitions drones par contre ne sont pas prises en compte du tout.

**Comment by Zakarik** [comment]
Sera ajouté à la prochaine mise à jour.
