### ISSUE TITLE
[Bug] Fiche PNJ et Créature

### ISSUE THREAD

**Issue by Kyrantox** [Zakarik/foundry-knight#194]
Salut Zakarik,

Gros problème côté fiche PNJ, les jets sont tout cassé.

Pour les fiches PNJ, les AE de la bête ne sont plus pris en compte. De plus, il y a la Chair des PNJ qui intervient sans que je sache pourquoi. Et donc le comportement du bouton pour ajouter la moitié de la Chair est lui aussi impacté.

![image](https://github.com/user-attachments/assets/786e213f-ece6-4afd-bf3e-4778cae11291)

![image](https://github.com/user-attachments/assets/2ed17ee8-bac6-4a6c-9729-f8b682aea626)

Pour les créatures, le problèmes est un peu plus cocasse, ils ne peuvent plus lancer leurs dommages pour leurs armes de corps à corps ni choisir leur aspects. De plus, lorsque l'on souhaite faire un jet depuis l'onglet "Aspect", impossible de changer d'Aspects une fois la fenêtre ouverte.

La fenêtre de pop up des jets est également un peu buggé aussi (vachement étiré à l'ouverture).

![image](https://github.com/user-attachments/assets/10d435b3-1a90-40f2-9a21-8ef42d335538)

Sauve nous des vilains bug Zakarik !

**Comment by Zakarik** [comment]
Sera corrigé lors de la prochaine mise à jour.
