### ISSUE TITLE
[Bug] Effet Orfèvrerie et Lesté pour PNJs / Créatures

### ISSUE THREAD

**Issue by Kyrantox** [Zakarik/foundry-knight#196]
Salut Zakarik,

Lorsque la valeur d'un des effet cité est impair, la calcul fait un résultat en X,5 et pas un arrondi au supérieur.

Lesté (pour 5 en Chair)
![image](https://github.com/user-attachments/assets/aed60c64-aa2a-46ca-b9e2-f05c907cc53c)

Orfèvrerie (pour 7 en Masque)
![image](https://github.com/user-attachments/assets/f587a0ea-c7f9-451e-b2f6-5cac5d9c62dd)

Bon courage ;)

**Comment by Zakarik** [comment]
Corrigé dans la prochaine mise à jour.
