### ISSUE TITLE
[Bug] Le bouton Dégâts pour toutes les cibles

### ISSUE THREAD

**Issue by Kyrantox** [Zakarik/foundry-knight#198]
Salut Zakarik,

Le bouton n'applique les dégâts qu'à la dernière cible de ce que je comprend.

Bon courage ;).

**Comment by Florleseige** [comment]
Bonjour Kyrantox,

Le bouton "Dégâts pour toutes les cibles" permet d'ouvrir toutes les fenêtres de dégâts pour toutes les cibles sélectionés.
Tu peux vérifier pour chaque fenêtre le nom de la cible en haut dans le titre, ex : "Knight • Dégâts au Joueur : Kyrantox"

Si tu constates un autre fonctionnement, explique nous :)

**Comment by Kyrantox** [comment]
En gros je fais faire un étape par étape, désolé pour le ticket peu concis, j'étais en partie hier quand j'étais en train de les ouvrir.

Mes 3 entités : 

![image](https://github.com/user-attachments/assets/e14e0151-8228-459b-8e4e-46875cf8f91d)

Le scénario est simple, A attaque B et C. Et on peut le voir qu'il touche les deux.

![image](https://github.com/user-attachments/assets/fb008793-8872-4a53-a0c1-5e6fd6b26154)

Je lance donc les dégâts.

![image](https://github.com/user-attachments/assets/b766ba94-28e2-4492-ba2d-7d37a6a21e11)

Et lorsque je clique sur "Dégâts pour toutes les cibles", j'ai bien les deux fenêtres.

![image](https://github.com/user-attachments/assets/15b27623-e406-4338-a44d-eb74e4c18da9)

![image](https://github.com/user-attachments/assets/7146f164-34e3-4e5c-a796-d6af7c7d922f)

Si je clique sur calculer sur les deux fenêtres, seul la deuxième cible reçoit les dommages, la première est ignoré.

![image](https://github.com/user-attachments/assets/75ba0b44-8b02-4975-bd70-9f54e4844405)

Et des tests que j'ai pu faire, même avec plus de cible, c'est toujours la dernière cible qui peut recevoir ses dommages automatiquement, le calcul ne se lance pas pour les autres.

**Comment by Zakarik** [comment]
Bug résolu dans la prochaine mise à jour.
