### ISSUE TITLE
[Bug] L'activation d'un module qui créer une arme change les valeurs des fiches PNJ

### ISSUE THREAD

**Issue by Kyrantox** [Zakarik/foundry-knight#200]
Salut Zakarik,

Tout est dans le titre : 

![image](https://github.com/user-attachments/assets/1d27963f-668b-4656-8adb-8ace187e0a13)

![image](https://github.com/user-attachments/assets/abf74a8a-62e3-4fa8-8bbd-de5ebd4caa6a)

Bon courage ;)

**Comment by Zakarik** [comment]
Sera corrigé dans la prochaine mise à jour.
