### ISSUE TITLE
[Bug / Suggestion] La partie option des fiches PJ

### ISSUE THREAD

**Issue by Kyrantox** [Zakarik/foundry-knight#201]
Sakut Zakarik,

Après être passer en V12 (ne te moque pas trop stp), j'ai rencontré un problème trop marrant sur l'option pour masquer les boutons de restauration sur les fiches, les MJ sont également compris dans l'exclusion.

![image](https://github.com/user-attachments/assets/9c22a2f5-f9be-4e9a-bbc5-0bd7532673dc)

![image](https://github.com/user-attachments/assets/b7511685-ffed-4d83-9442-c3d5e5be06b4)

Pour ce qui est de la suggestion, je pense qu'il serai pertinent d'étendre cette interdiction sur tout l'onglet "option" des fiches. Les joueurs ne devrait pas avoir accès à ce qui est système je pense. Je pense surtout à l'ajout de la Kraken notamment.

Bref, bon courage ;)

**Comment by Zakarik** [comment]
Corrigé dans la prochaine mise à jour.
