### ISSUE TITLE
[Bug] Bonus de ghost non appliqué au toucher/dégâts

### ISSUE THREAD

**Issue by Angor-de-Redjak** [Zakarik/foundry-knight#202]
Quand je fais des attaques avec mon PJ Rogue avec le mode Ghost activé, les bonus du mode Ghost ne sont pas présents ni dans le toucher, ni sur les dégâts.
J'ai même réimporté la Rogue sur la fiche histoire d'être sûr. Problème global ou juste sur la fiche ?

La fiche pour vérifier : [fvtt-Actor-shinichi-hizamaru-zIAmr82MqjIi9LZn.json](https://github.com/user-attachments/files/17536129/fvtt-Actor-shinichi-hizamaru-zIAmr82MqjIi9LZn.json)

Petite remarque d'ailleurs, je trouvais bien pratique le fait que sur les précédentes versions, les bonus étaient directement indiqués sans avoir besoin de survoler le résultat du jet.
![image](https://github.com/user-attachments/assets/1b02a4ce-7e8b-496f-b094-b9fc44848a8a)

**Comment by Zakarik** [comment]
Corrigé dans la version qui vient de sortir.
