### ISSUE TITLE
[Bug] Baisser la résilience

### ISSUE THREAD

**Issue by Angor-de-Redjak** [Zakarik/foundry-knight#205]
Et oui, c'est encore moi-

Knight 3.41.1
Foundry V12 Stable

On a observé un problème un peu mystique à ma table sur les créatures bénéficiant de la règle de résilience.

Normalement, un PJ ne doit pouvoir réduire la valeur de résilience que s'il entreprend de faire baisser la résilience aka : 
- 3 succès bonus au toucher
- seul la **violence** peut diminuer la stat de résilience, avec basiquement [violence/10] nombre entier la valeur en moins au score de résilience.
- le seul cas où les points de dégâts comptent sur la résilience, c'est s'il s'agit d'un **PNJ**

Hors on peut constater qu'en l'état, n'importe quelle méta-armure qui fait un jet de dégâts diminue la stat de résilience, ce qui n'est pas normal. (Ici une Rogue) En plus, ça ne touche même pas la santé de la cible.
![image2](https://github.com/user-attachments/assets/d28aad92-5868-42e3-afad-b28d7ba2ee05)
(D'ailleurs Chêne sculpté n'est pas automatiquement ajouté alors que la cible est un colosse. Je ne sais pas si c'est pas encore implémenté ou si c'est un bug...)

Là où ça devient incroyable, c'est avec la Barbarian en mode Goliath. La première entrée est faite sans anti-véhicule et la seconde est faite avec anti-véhicule.
![image3](https://github.com/user-attachments/assets/b167e37a-9936-4f87-9be4-2bc3d9b04e1d)
Normalement, anti-véhicule permet de bypass le trait Colosse et donc ignore la résilience. Sauf que dans le second jet, la résilience est toujours décomptée et du coup les dégâts infligés aux PS ne font aucun sens...

Proposition : est-ce qu'il ne serait pas envisageable de rajouter un bouton sur la fenêtre de jet d'attaque "Baisser la résilience" qui donne 3 succès bonus et ne laisse que le bouton pour lancer la violence et pas celui des dégâts (en tout cas pour les PJs).

D'ailleurs, la règle de résilience étant optionnelle, est-ce qu'il ne serait pas préférable de l'ajouter en option dans les options du système ?

Merci de m'avoir lu 🙏

**Comment by Florleseige** [comment]
Bonjour @Angor-de-Redjak ,
Cela va arriver dans la mise à jour de demain, si tu peux tester et bien me confirmer que tout fonctionne de ton coté quand tu auras fait la mise à jour je suis preneur :)

**Comment by Angor-de-Redjak** [comment]
Si c'est la mise à jour déployée, ça semble fonctionner correctement !
Merci pour le dur labeur 🙏

**Comment by Zakarik** [comment]
La dernière correction ayant été merge (et vu que ça semble fonctionner), je clos.
N'hésites pas à créer une autre issue si jamais :)
