### ISSUE TITLE
[Bug] capacités PNJ

### ISSUE THREAD

**Issue by Kyrantox** [Zakarik/foundry-knight#208]
Salut Zak,

Je me suis rendu compte que les capacité des PNJ qui donne un bonus à la santé ou à l'armure ne fonctionne pas.
Pareil pour augmenter l'aspect le maximum d'aspects (d'ailleurs les aspects ne sont plus limité à 20, on peut renseigner ce que l'on veut).
Et vu que je n'arrive à rien avec le bouton "ajoute un aspects au capacités liées à un aspect", j'imagine qu'il ne fonctionne pas aussi.
J'en profite pour dire qu'il faudrait aussi à terme intégré tous ce qui est protégé, serviteur tueur du seigneur etc pour le calcul des dommages. (et oui Florleseige je n'oublie pas de te donner du travail à toi aussi)

Bon courage ;).

**Comment by Florleseige** [comment]
Bonjour,
Pour les capacités du seigneur, je dois attendre du travail de la part de Zakarik.
Mais c'est dans ma TODO list.

**Comment by Kyrantox** [comment]
Je vois que monsieur est bon. Veuillez m'excuser de vous avoir importuné mon seigneur.

**Comment by Zakarik** [comment]
Les bugs mentionnés ont été corrigés.
