### ISSUE TITLE
Problemes d'évolutions de la Warlock

### ISSUE THREAD

**Issue by Evalflower** [Zakarik/foundry-knight#219]
Hello,

L'évolution 150PG de la Warlock "Désormais, les coûts en PE des modes Rewind et Record sont diminués de 3" ne s'appliquent pas  (passage de 12 à 9 pour record et de 15 à 12 pour rewind)

L'évolution 250PG de la Warlock ne s'applique pas sur foundry (Ne peut pas relancer les 2D6)
![image](https://github.com/user-attachments/assets/cd6e7af3-d20d-43ab-b733-64a69ed5b0e6)

**Comment by Zakarik** [comment]
Problème de compendium.
Corrigé dans la prochaine version du compendium.

**Comment by Zakarik** [comment]
Je ne l'ai pas précisé, mais il faut y corriger à la main sur les personnages ! Je ne corrigerai que dans le compendium.
