### ISSUE TITLE
[Bug] Bouton "Restaurer tous les chargeur"

### ISSUE THREAD

**Issue by Kyrantox** [Zakarik/foundry-knight#221]
Salut Zak,

Comme tu l'auras deviné dans le titre, le bouton restaurer tous les chargeurs n'a pas le comportement attendu.
Chez moi, il ne recharge pas les modules comme le pod de fusées éclairantes par exemple.

Bon courage ;).

**Comment by Zakarik** [comment]
Corrigé dans la prochaine version.
