### ISSUE TITLE
[Bug] Text field not getting translated

### ISSUE THREAD

**Issue by NarumiRM** [Zakarik/foundry-knight#222]
I've found that the field "DebordementAugmente" (line 2231 of translation files) doesn't get correctly translated as it shows the original French text regardless of chosen language.

Tested using Spanish translation module and English built-in translation:
![Captura desde 2024-12-15 12-38-24](https://github.com/user-attachments/assets/970e0774-72f7-4a2d-8f20-d34684dc2354)

**Comment by Zakarik** [comment]
Fixed !
