### ISSUE TITLE
probleme mode cea

### ISSUE THREAD

**Issue by Tenariel** [Zakarik/foundry-knight#46]
Dans la version 1.7.4, le mode cea empeche tout jet de l'armure.

Mode de reproduction:
- créer un nouveau chevalier
- ajouter une arme => possible de faire une attaque avec
- créer une armure avec la capacité céa ou utiliser le compendium pour ajouter l'armure monk
- l'arme ne peux plus être utiliser et aucun jet ne peut être fait depuis la fiche de perso (jet de carac par exemple).
- supprimer l'armure de la fiche de perso
- l'arme peut être de nouveau utiliser 

Enfin, dans les précédente version, j'ai pu voir que le mode CEA avait les malus des postures (akimbo et ambidextre). Hors d'apres la foire au question sur le discord officiel, on a comme réponse :

>  Q4 : - Questions concernant le mode Céa de la Monk :
> - Il est indiqué "sans aucun malus" concernant une attaque en ambidextre, de quels malus parle-t-on ?
> - Une attaque au Corps à Corps avec le gantelet de l'armure directement, activant par la même son mode Céa, ajoute-t-il sa Force aux dégâts ? Est-elle concernée par la règle d'une attaque "corps à corps" du LdB avec un ajout de 1D6 supplémentaire du fait de se battre en armure (LdB 1.5, p. 412, "Une claque dans Knight") mais "sans arme" ?
> 
> R4 : - La Monk n'a aucun malus dû au style ambidextre lors de l'utilisation du mode Céa
> - Les statistiques de l'arme sont à utiliser tels quels, sans modification, à moins d'un module

Magnifique travail en tout cas !

**Comment by Zakarik** [comment]
Normalement, c'est corrigé.
Concernant les malus, j'ai juste retiré celui du mode ambidextrie, vu que c'est le seul mode dont il est question dans la réponse.

**Comment by Tenariel** [comment]
Merci pour la correction (je confirme le fix de mon probleme).

pour moi la réponse officiel pour la posture ambidextre doit être la même que pour la posture akimbo vu que c'est le même type de malus (ainsi l'arme est a utiliser sans modification tant qu'un module ne change les valeurs). 

Ceci étant dit, ceci est >ma< réponse et effectivement n'est pas indiqué dans la réponse officiel.
