### ISSUE TITLE
Longbow Evolution and Customisation

### ISSUE THREAD

**Issue by Sulion1248** [Zakarik/foundry-knight#54]
Lors de l'ajout d'une évolution du longbow la description de l'arme disparait
Lors du choix entre les améliorations du longbow les libellés de 3 des augmentations sont identiques
Le décompte en PG d'une amélioration du longbow ne peut pas passer en gratuit
L'ajout d'amélioration d'arme à distance n'est pas possible sur le longbow

**Comment by Zakarik** [comment]
J'ai résolu le problème pour la description.
J'ai résolu le problème pour le libellé des améliorations du longbow.

Pourquoi faudrait-il y passer en gratuit ? Ca coûte toujours de la gloire de passer ces évolutions.

Je vais voir ce que je peux faire pour les améliorations d'armes à distance.

**Comment by Sulion1248** [comment]
Lors de la création du personnage on bénéficie de PG gratuit qui peuvent être utilisé pour l'achat de ces améliorations mais ne sont pas décompté dans les PG totaux

**Comment by Zakarik** [comment]
Je vais voir ce que je peux faire.
