### ISSUE TITLE
Jet d'arme en privée

### ISSUE THREAD

**Issue by Aramid** [Zakarik/foundry-knight#56]
Les jets de dés des armes ne prennent pas en compte le mode de jet de dé sélectionné sur Foundry (Private etc...) et sont forcément en public.

D'après DjLeChuck du discord "La Fonderie", il faudrait que les messages soit de type "ROLL" plutôt que de type "OTHER" (comme c'est le cas actuellement). Aucune idée de la masse de travail que ce changement représente.

**Comment by Tenariel** [comment]
je me permet de rajouter comme info que les rolls de PNJ eux ont l'air de fonctionné correctement (private roll etc ...).

**Comment by Zakarik** [comment]
Ca devrait être réglé.
