### ISSUE TITLE
Dégats sur le mode Ghost

### ISSUE THREAD

**Issue by LouisGaboury** [Zakarik/foundry-knight#63]
Merci du retour éclair sur les précédents tickets ! Voici le nouveau

Lors d'une attaque alors que le mode Ghost est activé, il n'y a pas de dégats supplémentaires infligés via ce mode. 
Extrait du mode Ghost : _Les attaques de combat ou de tir (uniquement avec des armes de tir possédant l’effet silencieux et toutes les armes de combat sauf celles possédant l’effet lumière) reçoivent cependant un bonus en dés au test et en bonus fixe aux dégâts égal à la Discrétion du porteur, overdrives compris (le score de Discrétion s’ajoute une nouvelle fois dans le combo si ce score est déjà utilisé pour l’attaque, de plus ce score s’ajoute aux dégâts en plus des bonus déjà octroyés par l’effet silencieux ou le niveau 2 de l’overdrive de Discrétion). Seule la première attaque du tour du personnage dispose de ces bonus._

Alors ça fait quand même beaucoup de conditions, pas sûr que ça soit facile d'ajouter ça mais ça serait toujours un plus agréable si y'a le temps et si c'est pas trop galère.

**Comment by LouisGaboury** [comment]
Me suis rendu compte d'un oubli important xD

_Lorsque le chevalier atteint 250 PG accumulés, il peut payer 3PE à chaque attaque pour maintenir son invisibilité et donc disposer des bonus ci-dessus._

Du coup ça change pas mal la condition de première attaque du tour

**Comment by Zakarik** [comment]
C'est étrange, car j'ai testé et je n'ai pas ce problème :
Contact : 
![image](https://user-images.githubusercontent.com/8583530/201670850-3a892080-abc9-4d01-8669-650e44df9ac1.png)
Distance :
![image](https://user-images.githubusercontent.com/8583530/201670997-8299c786-8be3-48d2-b9c1-438a001b5639.png)
