### ISSUE TITLE
Cout des améliorations d'armes non prise en compte

### ISSUE THREAD

**Issue by Mnemomos** [Zakarik/foundry-knight#66]
Bonjour

Sur les améliorations d'armes (a distance ou de contact)
Le pris en PG n'est pas pris en compte dans la progression
![image](https://user-images.githubusercontent.com/92275753/202722397-ec00b871-c947-4661-b09b-21aa08f25a4c.png)

![image](https://user-images.githubusercontent.com/92275753/202722693-158f6211-b158-456f-8fe8-2b9e2d5cfe8d.png)
On les rajoutent a la main comme ceci , on peut aussi le faire dans l'arme donc c'est pas un énorme soucis.

Bonne journée

**Comment by Zakarik** [comment]
Alors c'est normal, les deux façons de gérer ça, c'est en ajoutant à la main ou en augmentant le coût de l'arme.

Ce serait très fastidieux de traquer chaque amélioration d'arme pour les lier à un coût et rendrait le tout également moins flexible.
