### ISSUE TITLE
Véhicules : modules et armes

### ISSUE THREAD

**Issue by KageLetithord** [Zakarik/foundry-knight#67]
Lors de l'utilisation de véhicules en combat, comme le Vector Harpie par exemple, il semble impossible d'assigner un PJ passager sur les modules. Comme si la propriété enregistrant l'ID de l'actor n'était pas correctement liée dans l'HTML ?

Il y a également un problème sur le lancer des armes du véhicule. L'acteur peut bien être assigné à une arme, mais lors du clic sur "Lancer" dans la fenêtre secondaire, une erreur apparaît dans la console : 
![image](https://user-images.githubusercontent.com/26125340/202764485-cc227a50-24d8-44e7-94e3-43128d6b2b50.png)

Le problème est que sur cette ligne : 
`const aspects = actor.system.aspects;`
On récupère les "aspects" de l'acteur dont l'ID est fourni en paramètre de la fonction getCaracValue, en l'occurence, l'acteur est le véhicule, et non le personnage sur l'arme. Ce qui fait que cette propriété "aspects" est undefined.

**Comment by Zakarik** [comment]
Corrigé normalement, sauf ce que j'ai dis sur Discord.
En attente de réponse pour le reste, donc.
