### ISSUE TITLE
Munitions drones et succès autos

### ISSUE THREAD

**Issue by KageLetithord** [Zakarik/foundry-knight#68]
Les munitions drones n'ajoutent qu'une seule réussite auto supplémentaire
Les deux jets sont avec les mêmes stats cochées (Tir 5 + Technique 6 + OD Technique 2). On voit sur le deuxième jet qu'il n'y a qu'une seule réussite auto supplémentaire (non affichée dans le tooltip explicatif d'ailleurs) au lieu de 3.
![image](https://user-images.githubusercontent.com/26125340/202765905-fa7bc066-eef3-4e8f-833d-f774802c971c.png)

**Comment by Zakarik** [comment]
Corrigé.
