### ISSUE TITLE
Armure Paladin et mode Watchtower

### ISSUE THREAD

**Issue by KageLetithord** [Zakarik/foundry-knight#69]
L'utilisation du mode Watchtower dépense bien l'énergie, mais ne s'affiche pas comme activée (cf image 1 avant, et image 2 après activation)
![image](https://user-images.githubusercontent.com/26125340/202766515-b6e13d04-b294-470a-a812-35d30086ec86.png)
![image](https://user-images.githubusercontent.com/26125340/202766549-0be20493-98da-4e07-a9cc-cd30d84de773.png)

**Comment by Zakarik** [comment]
Corrigé.
