### ISSUE TITLE
Proposition d'amélioration : Munitions activées / désactivées

### ISSUE THREAD

**Issue by KageLetithord** [Zakarik/foundry-knight#70]
Une suggestion, qui peut amener à débat, il s'agit peut-être d'une préférence d'affichage.
Les munitions, sur la fenêtre secondaire, de préparation du lancer ont un affichage à 2 boutons. Le code couleur pour différencier leur statut n'est pas assez intuitif (à mon humble avis), nous obligeant à vérifier à chaque fois. D'autant plus qu'elles sont actives par défaut.

Est-ce que cet aspect pourrait être modifié, éventuellement avec un unique bouton "Munition activée"/"Munition désactivée", ou un code couleur plus voyant, ou avec un bouton de type toggle (avec couleurs différenciables)/checkbox/... 
Aussi, les mettre en désactivées par défaut, en cas d'oubli cela créé une situation où toutes les munitions sont actives par défaut
![image](https://user-images.githubusercontent.com/26125340/202767544-b3bea2d2-22a7-4aeb-bf68-d84dc4006435.png)

**Comment by Zakarik** [comment]
J'ai fais un essai d'amélioration de la lisibilité en diminuant l'opacité de la case non sélectionnée, dis-moi ce que tu en penses.

**Comment by KageLetithord** [comment]
C'est un peu plus lisible, en effet. Je proposerai tout de même une police plus grande, pour que ce soit plus accessible.
![image](https://user-images.githubusercontent.com/26125340/202824631-662cadc6-65a2-4100-9097-bc4ce72b1d67.png)
(line-height à 20px et font-size à 15px pour ce rendu).

Pour détail sur la proposition d'inverser le statut par défaut : cela permettrait aussi, en cas de multiple munitions sur une même arme, de devoir effectuer plusieurs clics superflus pour tout désactiver (sauf une éventuellement). Que penses-tu de cette proposition du coup ?

**Comment by Zakarik** [comment]
D'accord pour agrandir, par contre, je ne pense pas que désactiver par défaut soit une bonne idée, parce que la plupart des tirs, d'expérience, se font avec toutes les munitions activées.

C'est plus facilement les cas spécifiques qui implique de désactiver une ou plusieurs munitions.
