### ISSUE TITLE
Revêtement oméga : tir impossible

### ISSUE THREAD

**Issue by KageLetithord** [Zakarik/foundry-knight#71]
Lorsque l'amélioration Revêtement Oméga est installée sur une arme, le tir génère une erreur
![image](https://user-images.githubusercontent.com/26125340/202793071-8e0e996c-af62-4795-8990-38fdce1da323.png)

Le problème montré est que la propriété "assassin" est undefined. 
```javascript
case 'revetementomega':
        const vAssassin = +assassin.split(' ')[1];
```

**Comment by Zakarik** [comment]
Corrigé.
