### ISSUE TITLE
Bug de la Sorcerer (plus quelques petits autres choses)

### ISSUE THREAD

**Issue by FlorianAubin** [Zakarik/foundry-knight#77]
Bonjour,

Déjà GG pour le super taf sur le système Knight! Avec ma team on est entrain de transiter vers ce système.

J'ai remarqué quelques bugs et choses qui serait cool d'ajouter (la partie concernant le système de mon commentaire sur discord) :
 - le mode morph de la Sorcerer est pas mal buggé (c'est un peu le point principal de mon message, le reste c'est plus des détails que je fais remonter) : 
     - le cout en Espoir ne s'applique pas 
     - le bonus de Réaction et de Défense de "Corps fluide" ne disparait pas quand on désactive le mode (alors que le bonus de CDF de "Corps de métal" si)
     - quand on fait un jet pour maitriser un adversaire, on gagne +3 réussites auto (Étirement). Mais ensuite ce bonus est toujours présent pour les autres jets. Et il ne disparait pas non plus quand on désactive le mode
     - on est censé pouvoir modifier gratuitement les modules de "Polymorphie de Guerre" à chaque tour, alors qu'avec le mode tel qu'il est, on est obligé de désactiver et réactiver tout le mode (avec les couts en énergie et normalement en espoir qui vont avec)
     - pas vraiment des bugs, mais ça pourrait être sympa de pouvoir : 
        - quand on active "Phase", il pourrait y avoir 1 ou 2 boutons supplémentaires qui apparaissent pour activer le module de phase lvl 1 ou 2 (avec les couts en PE auto)
        - avoir un bouton pour lancer les 1 à 3d6 de récupération d'énergie d'une armure alliée
 - le mode Candle de la Berserk ne fonctionne pas (rien ne se passe quand on clique sur le bouton)
 - le mode Lantern de la Berserk ne lance pas de dés
 - d'autres choses qui ne sont pas des bugs, mais qui pourrait simplifier un peu la vie : 
     - la diminution auto du nombre de grenades quand on en utilise une (comme ce qui est déjà fait pour les nodes)
     - pouvoir réorganiser les modules dans les fiches perso (ça devient vite le bordel ^^)
     - avoir un bouton pour réinitialiser les valeurs par défaut (PV, PE, PA, nodes, grenades...)

**Comment by Zakarik** [comment]
Une grande partie est normalement résolu, je note ce qu'il reste (pour moi), et donc tout ce que je n'écris pas devrait être corrigé :

- pouvoir réorganiser les modules dans les fiches perso (ça devient vite le bordel ^^)
- quand on active "Phase", il pourrait y avoir 1 ou 2 boutons supplémentaires qui apparaissent pour activer le module de phase lvl 1 ou 2 (avec les couts en PE auto)
-  avoir un bouton pour lancer les 1 à 3d6 de récupération d'énergie d'une armure alliée

**Comment by FlorianAubin** [comment]
Merci :)
Le bonus de +3 d'Étirement persiste encore sur les autres lancers (désolé de casser l'ambiance). Le reste semble fonctionner !

Concernant la possibilité de réorganiser les modules (ou armes ou tous autres items liés à un acteur), j'ai vu que l'API de Foundry avait déjà une fonction toute prête pour ça. Il "suffit" de mettre la classe html "item" aux div qui correspondent aux item, et "item-list" à la div (ou table ou autre) qui les contient. Ensuite on peut les réorganiser en drag and drop les items les uns sur les autres.

**Comment by Zakarik** [comment]
Effectivement pour l'étirement.
J'ai essayé pour item-list, mais ça ne semble pas fonctionner, donc il doit manquer quelque chose.
Tu as eu où cette information ?

**Comment by FlorianAubin** [comment]
Dans le tuto youtube de Cédric Hauteville, part 11, au début de la vidéo : 
https://www.youtube.com/watch?v=hjlzKGNRwbQ&list=PLFV9z59nkHDccUbRXVt623UdloPTclIrz&index=13

**Comment by Zakarik** [comment]
J'ai amélioré ça :
 - Le bonus de +3 d'Étirement persiste encore sur les autres lancers
 
 Il ne reste donc que :
-  quand on active "Phase", il pourrait y avoir 1 ou 2 boutons supplémentaires qui apparaissent pour activer le module de phase lvl 1 ou 2 (avec les couts en PE auto)
- avoir un bouton pour lancer les 1 à 3d6 de récupération d'énergie d'une armure alliée

**Comment by Zakarik** [comment]
Dans la prochaine version, il y aura :
L'activation de la Phase
Les boutons pour ponctionner l'énergie.
Pour ce dernier point, il faudra rajouter soi-même le spécial "Énergie déficiente" à l'armure.

Pour la phase, il n'est toujours pas possible de choisir entre niv 1 ou 2, mais c en'est déjà pas le cas avec le module...
Ce n'est pas non plus totalement clair de si le niveau 2 rajoute juste une action optionnelle à 8PE ou si c'est l'action principale qui passe à 8PE et qui gagne un effet supplémentaire.

Ce dernier cas rendrait ce module unique en son genre, c'est pourquoi je ne sais pas trop.

**Comment by FlorianAubin** [comment]
Super !
Pour la phase, j'ai l'impression (mais je peux me tromper) que le niveau 2 ajoute une action à 8 PE.

**Comment by Zakarik** [comment]
Pour la prochaine version, il y aura enfin le niveau 2 de la phase de manière indépendante !
Donc je clos ce ticket, car je crois que c'était la dernière chose qu'il restait.
