### ISSUE TITLE
Effet d'améliorations structurelles

### ISSUE THREAD

**Issue by Kyrantox** [Zakarik/foundry-knight#78]
Bonjour,

J'ouvre cette issue pour mettre en lumière deux soucis que j'ai rencontrés lors de la personnalisation des modules de mes joueurs.

Le premier problème est que les améliorations structurelles n'appliquent pas les effets sur les modules (les griffes de combat dans mon cas). C'est le cas pour 100% des améliorations structurelles. J'ai donc décidé de contourner le problème en rajoutant les effets à la main.

Ce qui me conduit au deuxième problème. Certains effets ne sont pas présents dans la liste telle que l'effet de l'amélioration "Sur mesure". J'ai donc voulu créé un effet personnalisé, cependant, sur les modules, la liste déroulante n'affiche rien. Ce problème n'est présent que sur les modules.

![image](https://user-images.githubusercontent.com/43754117/226390004-287f5516-78d4-4d06-b4ed-872b13c057e6.png)

En espérant, que ces soucis ne soient pas une tanné à régler pour vous.
Merci encore pour le reste du système, il est fou.
Bon courage pour la suite.

**Comment by Zakarik** [comment]
Normalement résolu.
