### ISSUE TITLE
Problème fiche de personnage 3.3.17

### ISSUE THREAD

**Issue by Touakami** [Zakarik/foundry-knight#83]
Bonjour,
Pour commencer, j'aimerai te remercier pour la mise en place de ce système sur foundry, qui est niquel, donc merci pour ton travail ! 
Depuis la MaJ 3.0, j'expérimente de nombreux bugs sur les fiches de mes personnages actuellement. Je suis en 3.3.17 pour bénéficier des différents correctifs mais j'obtiens les problèmes suivants : 
- Dans certaines fiches de personnages, je n'ai plus accès aux modules (voir capture PB1)
- Dans le cas ou j'ai l'accès aux modules de mes fiches de personnages, le calcul des slots n'est plus bon (sans modules, j'ai déjà des slots de prit) (voir capture PB2)
- Revenir à une version antérieur ou créer un nouveau personnage ne fonctionne pas : soit le PB 1 ce produit, soit je ne peux plus glisser de module dans la fiche.
![PB1 - Problème accès modules](https://user-images.githubusercontent.com/130212638/230711400-ac279c70-6fd7-4f0a-afd6-08d6f27f40a5.png)
![PB 2 - Modules](https://user-images.githubusercontent.com/130212638/230711402-c937fedf-4aad-42ed-9822-0b4ad974ef97.png)

Merci d'avance pour ton retour à ce sujet ! Je reste disponible si besoin de plus de détails,

**Comment by Zakarik** [comment]
Il y a eu des patchs qui peuvent avoir amélioré les choses depuis.
Si ce n'est pas le cas, pourrais-tu m'envoyer le monde sur lequel le problème se trouve, que je vois chez moi ?
Merci

**Comment by Touakami** [comment]
Hello ! 
Merci pour ton retour !
Avec les dernières mises à jours, je peux recréer des fiches avec l'onglet Module qui apparait ! 
En créant de nouvelles fiches, l'énergie avec le NaN est corrigé, mais apparait dans la Gloire maintenant.
Pareil avec les nouvelles fiches, je tombe bien à 0 partout en module. Impossibilité de glisser les modules dans les fiches, mais je pense que ca viendra dans un prochain patch ! 

Au besoin, je te joins le zip de mon monde dans le mail, si cela peut t'aider ^^

[ForgeVTT-export-knight-promethee-2023-04-08_22_7_10.zip](https://github.com/Zakarik/foundry-knight/files/11184311/ForgeVTT-export-knight-promethee-2023-04-08_22_7_10.zip)

Merci encore pour ton travail et ton soutien !

**Comment by Zakarik** [comment]
Normalement avec la dernière mise à jour qui vient d'avoir lieu, les bugs doivent tous avoir été réglés.

**Comment by Touakami** [comment]
Hello,
Je confirme que tout est bon ! Merci pour ton aide ! :)
