### ISSUE TITLE
Décompte des PG/PX dans l'autre sens

### ISSUE THREAD

**Issue by Relkem** [Zakarik/foundry-knight#85]
Hello,

Sur la fiche j'ai qu'un seul fonctionnement que j'ai du mal à saisir, c'est le décompte des PG et des PX. 

La seule case remplissable est la case actuel, forçant à chaque achat à faire le décompte de point actuel restant.

Ne serait-il pas plus intuitif de mettre en case modifiable la case de valeur total ? 

Egalement pour l'augmentation des aspects/caracs pourrais tu imaginer un fonctionnement proche de celui des modules avec niveau ? en prenant les premières vlaurs (les caracs et aspects de bases) en gratuit, et les monté d'après avec le coût calculé automatiquement (2 points fois le niveau de carac visé et 5 points fois le niveau d'aspect visé) ?

**Comment by Zakarik** [comment]
Pour ce qui est de la dépense des PG, ça pourrait être possible, il faut que je voie.
Pour l'autre, c'est envisagé, mais il faut prendre en charge les exceptions, c'est pour ça que ce n'est pas encore implémenté, et qu'en attendant, le coût est à rentrer manuellement.

Je laisse ouvert pour le moment, du coup.

**Comment by Relkem** [comment]
Ah j'avais pas fait attention aux exceptions de coût d'acquisition...

En tout cas top pour les PG.
