### ISSUE TITLE
Overdrive en tenue civile

### ISSUE THREAD

**Issue by Mnemomos** [Zakarik/foundry-knight#87]
Bonjour, j'ai un OD de Combat sur un personnage (ce qui est normal) mais je l'ai également en Guardian et Tenue Civile

![image](https://user-images.githubusercontent.com/92275753/231587169-b8263c90-3775-4ba5-9587-402c58a7b037.png)

![image](https://user-images.githubusercontent.com/92275753/231587223-d9059614-75a6-4cb2-a818-4cdef0920aa2.png)
en mettant l'OD a un lvl supérieur a 1, j'ai toujours 1 od de technique en civil (en méta-armure, ça monte normalement)
mais quand je supprime l'OD, il se retire bien, du Priest ou de la tenue civile.

Je mets le json au cas-ou
[fvtt-Actor-taylor.zip](https://github.com/Zakarik/foundry-knight/files/11216078/fvtt-Actor-taylor.zip)

**Comment by Mnemomos** [comment]
Ce n'est pas que sur ce personnage, j'ai bien fait attention a récupérer les modules du compendium.
![image](https://user-images.githubusercontent.com/92275753/231588305-ae588be9-f93b-4765-92e9-a26e564a414a.png)

**Comment by Zakarik** [comment]
Ca devrait être corrigé.
