### ISSUE TITLE
Rogue : bonus bouton "Passer inaperçu" permanent

### ISSUE THREAD

**Issue by Florleseige** [Zakarik/foundry-knight#89]
Sur la Rogue Mode Ghost, lorsque l'on clique sur le bouton "Jet: Passer inaperçu", on a un bonus de 3 succès automatiques qui se rajoute.
Mais par la suite, ce bonus ne disparait pas et les joueurs oublis de l'enlever.
Pouvons nous faire en sorte de l'enlever automatiquement si on ne clique pas sur ce bouton ?

Merci d'avance.

**Comment by Zakarik** [comment]
J'ai rajouté le fait que ce bonus soit retiré automatiquement après le jet.
