### ISSUE TITLE
Problème avec l'Arme sur tourelle

### ISSUE THREAD

**Issue by FloAddWorking** [Zakarik/foundry-knight#90]
Bonjour,

Lorsque l'on fait un jet avec une Arme qui est sur une tourelle d'épaule, les caractéristiques ne sont pas sélectionnés dans le lancement des dès.
Cela lance systématiquement 1d6+0

**Comment by Zakarik** [comment]
C'est normal, les armes sur tourelles sont pour les armes ayant un jet d'attaque fixe.
Une fois qu'une arme est montée sur tourelle. Elle possède, dans ses options, un endroit pour rentrer le jet d'attaque.
Néanmoins, j'ai amélioré la clarté de l'affichage sur la fiche du personnage.
