### ISSUE TITLE
Armure Warmaster Impulsion : problème clef de traduction

### ISSUE THREAD

**Issue by Florleseige** [Zakarik/foundry-knight#93]
Bonjour, 

Dans l'armure Warmaster, au niveau de la description de l'impulsion d'action, il y a une clef de traduction qui ne fonctionne pas dans le champ : "Activation".

**Comment by Zakarik** [comment]
J'ai mis en place quelques vérifications qui devraient empêcher ou limiter l'apparition de ce genre d'artefacts visuels.
