### ISSUE TITLE
Bug Armure Monk, attques d'energie

### ISSUE THREAD

**Issue by Phaerim** [Zakarik/foundry-knight#94]
Créer un personnage joueur
L'équiper d'une armure monk
Oglet Combat > Lancer la fenetre de combat avec Vague d'énergie
Selectionner Le combot et une attaque liée à l'armure (Vahue, Salve ou Rayon d'énergie) puis cliquer sur "Jet normal"
Attendu : Un jet se lance
Obtenu : Rien ne se passe

Console après des essaies de lancé de dès :
![image](https://user-images.githubusercontent.com/15880906/232318883-f7a38b81-8163-4e7e-a922-a400badeeed5.png)

**Comment by Zakarik** [comment]
Corrigé dans la prochaine mise à jour.
