### ISSUE TITLE
Compatibilité Status Icon Encounter

### ISSUE THREAD

**Issue by Kyrantox** [Zakarik/foundry-knight#96]
Bonjour,

Je glisse juste ici que j'ai de nouveau un bug avec le module "Status Icon Encounter" sur ma table.

![image](https://user-images.githubusercontent.com/43754117/233788089-2f46d1fb-81ed-4d4a-838b-5115a00ba87d.png)

Et certain de mes joueurs ont de nouveau les erreurs qui y sont lié.

**Comment by Zakarik** [comment]
J'ai envoyé une correction.
N'ayant pas de quoi particulièrement testé si ça fonctionne ou non, il faudrait me le dire.

Pour que ça prenne effet, il faudrait désactiver les capacités d'armures et changer de style de combat (il s'agissait, à priori, des éléments qui manquaient dans la correction précédente).

**Comment by Kyrantox** [comment]
Et bien après avoir joué avec mes joueurs, apparemment, ils ont encore un peu des erreurs mais assez rarement (de l'ordre de 3 tout au plus). Par contre c'est compliqué de vous aider cette fois-ci car j'ai l'impression qu'elles apparaissent sans réellement de corrélation. De plus les PJ ont en effet plus le bug d'icône fantôme, par contre quelques PNJ l'ont mais je ne sais pas pourquoi là aussi (seul quelques PNJ, aucune créature etc).
Désolé d'avoir aussi peu d'informations à vous donner.

**Comment by Kyrantox** [comment]
Pardon, j'avais totalement oublié de répondre. Je n'ai visiblement plus le problème en effet, merci beaucoup
