### ISSUE TITLE
Jets cachés : Affichage des echecs critiques

### ISSUE THREAD

**Issue by Phaerim** [Zakarik/foundry-knight#97]
Bug mineur et potentiellement pas du système
Lorsque le MJ fait un jet caché et que celui-ci se solde par un échec critique, voice ce que voient les joueurs : 
![image](https://user-images.githubusercontent.com/15880906/233835781-9546575e-22f5-4989-8eca-a0c8d1126c4c.png)

**Comment by Phaerim** [comment]
J'ai testé sans addons et ai aussi eu l'affichage. Pour simuler l'échec
critique le meilleur moyen est de faire le jet sans avoir sélectionné
d'attribut. Je pourrais refaire le test demain.

**Comment by Zakarik** [comment]
Autant pour moi, j'ai trouvé le problème et corrigé ça.

**Comment by Phaerim** [comment]
T'es un boss !
