### ISSUE TITLE
Impossible de modifier des modules équipés

### ISSUE THREAD

**Issue by Kyrantox** [Zakarik/foundry-knight#98]
Bonjour, 

Suite à la dernière mise à jour, la 3.9.3. Je ne peux plus modifier des modules que j'équipe sur mes joueurs ou PNJ.

Merci encore pour votre travail.

**Comment by Zakarik** [comment]
Je n'ai pas ce bug chez moi, est-il possible de me fournir les données du personnage pour que je vois ça ?

**Comment by Kyrantox** [comment]
Tous mes PJ et PNJ ont ce problème, je vous envoie quel fichier ? actors.db ? Ou j'extrait les données d'un PNJ ?

**Comment by Kyrantox** [comment]
D'ailleurs en testant un peu, les anciens modules équipés peuvent être modifiés mais ceux que je rajoute maintenant ne le peuvent pas

**Comment by Zakarik** [comment]
Si vraiment tous ont le problème, actor.db, oui.

**Comment by Kyrantox** [comment]
Je vous l'ai passé sur discord, je n'arrive pas à l'envoyer ici.
