### ISSUE TITLE
Erreur de fonctionnement sur l'OD d'instinct 

### ISSUE THREAD

**Issue by alexpouteau** [Zakarik/foundry-knight#99]
Bonjour,
Je vous fait une petite erreur au niveau du fonctionnement de l'OD d'instinct. 
Au niveau 3 il devrait permettre d'ajouter +3 fixe au jet d'initiative par niveau d'OD, hors actuellement il ajoute +3D par niveau d'OD à jet d'initiative.

**Comment by Zakarik** [comment]
C'est corrigé !
